version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: decorator
    versions:
    - 5.0.6
  - dependency-name: scipy
    versions:
    - 1.6.1
